METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1
  
  lr: 0.001
  weight_decay: 0
  milestones: [12, 50]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200
  use_cl: False
  cl_step_size: 2500

  pass_device: True

  model_args:
    num_nodes: 207
    input_dim: 1
    output_dim: 1
    horizon: 12
    rnn_units: 64
    num_layers: 1
    cheb_k: 3
    adj_path: "../data/METRLA/adj_mx.pkl"
    adj_type: "doubletransition"
    device: null # will be updated

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1
  
  lr: 0.01
  weight_decay: 0.0001
  milestones: [12, 50]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  use_cl: False

  load_npz: False
  with_embeddings: False
  pass_device: True

  model_args:
    num_nodes: 325
    input_dim: 1
    output_dim: 1
    horizon: 12
    rnn_units: 64
    num_layers: 1
    cheb_k: 3
    adj_path: "../data/METRLA/adj_mx_bay.pkl"
    adj_type: "doubletransition"
    device: null # will be updated
    