METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True
  
  lr: 0.002
  weight_decay: 0.0001
  early_stop: 10
  milestones: [80, 100]
  clip_grad: False
  batch_size: 64
  max_epochs: 200
  use_cl: True
  cl_step_size: 2000

  pass_device: True

# If use meta_att only, addaptadj should be False

  model_args:
    device: None 
    num_nodes: 207
    in_dim: 2
    out_dim: 12
    # adj_path: "../data/METRLA/adj_mx.pkl"
    adj_path: False
    adj_type: "doubletransition"
    dropout: 0.3
    gcn_bool: True
    addaptadj: True
    aptinit: null
    node_emb_file: "../data/METRLA/spatial_embeddings.npz"
    tod_embedding_dim: 24
    dow_embedding_dim: 7
    node_embedding_dim: 64
    learner_hidden_dim: 128
    z_dim: 64
    add_meta_adj: True
    add_meta_att: False
    cheb_k: 3

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [80]
  clip_grad: False
  batch_size: 64
  max_epochs: 200
  use_cl: True
  cl_step_size: 2500

  pass_device: True

  model_args:
    device: None 
    num_nodes: 325
    in_dim: 2
    out_dim: 12
    # adj_path: "../data/PEMSBAY/adj_mx_bay.pkl"
    adj_path: False
    adj_type: "doubletransition"
    dropout: 0.3
    gcn_bool: True
    addaptadj: True
    aptinit: null
    node_emb_file: "../data/PEMSBAY/spatial_embeddings.npz"
    tod_embedding_dim: 24
    dow_embedding_dim: 7
    node_embedding_dim: 64
    learner_hidden_dim: 128
    z_dim: 64
    add_meta_adj: True
    add_meta_att: False
    cheb_k: 3
