METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True
  
  lr: 0.002
  weight_decay: 0.0001
  early_stop: 10
  milestones: [80, 100]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  use_cl: True
  cl_step_size: 2500

  pass_device: True

  model_args:
    num_nodes: 207
    in_dim: 2
    seq_length: 12
    out_dim: 12
    device: None # will be updated
    gcn_true: True
    buildA_true: False
    gcn_depth: 2
    # adj_path: "../data/METRLA/adj_mx.pkl"
    adj_path: null
    # predefined_A: null
    static_feat: null
    dropout: 0.3
    subgraph_size: 20 # topk
    node_dim: 40
    dilation_exponential: 1
    conv_channels: 32
    residual_channels: 32
    skip_channels: 64
    end_channels: 128
    layers: 3
    propalpha: 0.05
    tanhalpha: 3
    layer_norm_affline: True
    node_emb_file: "../data/METRLA/spatial_embeddings.npz"
    tod_embedding_dim: 24
    dow_embedding_dim: 7
    node_embedding_dim: 64
    learner_hidden_dim: 128
    z_dim: 64
    add_meta_adj: True
    add_meta_att: False    

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True
  
  lr: 0.002
  weight_decay: 0.0001
  early_stop: 10
  milestones: [60, 80]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  use_cl: True
  cl_step_size: 2500

  pass_device: True

  model_args:
    num_nodes: 325
    in_dim: 2
    seq_length: 12
    out_dim: 12
    device: null # will be updated
    gcn_true: True
    buildA_true: False
    gcn_depth: 2
    # adj_path: "../data/PEMSBAY/adj_mx_bay.pkl"
    adj_path: null
    # predefined_A: null
    static_feat: null
    dropout: 0.3
    subgraph_size: 20 # topk
    node_dim: 40
    dilation_exponential: 1
    conv_channels: 32
    residual_channels: 32
    skip_channels: 64
    end_channels: 128
    layers: 3
    propalpha: 0.05
    tanhalpha: 3
    layer_norm_affline: True
    node_emb_file: "../data/PEMSBAY/spatial_embeddings.npz"
    tod_embedding_dim: 24
    dow_embedding_dim: 7
    node_embedding_dim: 64
    learner_hidden_dim: 128
    z_dim: 64
    add_meta_adj: True
    add_meta_att: False    
    